### ISSUE TITLE
error in gse function 

### ISSUE THREAD

**Issue by yangkangyf** [GuangchuangYu/clusterProfiler#17]
When i run gse functions, such as ,
gsekegg <- gseKEGG(geneList = gse_mb_5,
                   organism = "human",
                   nPerm = 100,
                   minGSSize = 120,
                   pvalueCutoff = 0.01,
                   verbose = TRUE)
but always has errors,
 Error in if (abs(max.ES) > abs(min.ES)) { : 
   missing value where TRUE/FALSE needed

        Any suggestions?

**Comment by GuangchuangYu** [comment]
Can you send me a sample data so that I can reproduce you error?

**Comment by yangkangyf** [comment]
Thanks for your reply. I solved it by removed all NA

**Comment by DongqiangZeng0808** [comment]
[kk_gsea.zip](https://github.com/YuLab-SMU/clusterProfiler/files/3763147/kk_gsea.zip)
enrichplot::gseaplot2(kk_gsea,“PI3K-Akt signaling pathway”,
                subplots=c(1,2),
                base_size = 11,
                color = “red”, 
                pvalue_table = TRUE)
###############################
#Error in if (abs(max.ES) > abs(min.ES)) { : 
 #missing value where TRUE/FALSE needed

**Comment by DongqiangZeng0808** [comment]
I would really appreciate it if Pro. Yu could answer this question.

**Comment by GuangchuangYu** [comment]
```
enrichplot::gseaplot2(kk_gsea,"hsa04151",
    subplots=c(1,2),
    base_size = 11,
    color = "red",
    pvalue_table = TRUE)
```

**Comment by DongqiangZeng0808** [comment]
I solved it by setting the geneset ID as row names of the result.

**Comment by DongqiangZeng0808** [comment]
Thank you so much for your reply.  I got it. The geneset ID should be the row names of the result.

**Comment by Rikkiff** [comment]
Dear GuangchuangYu, 

I am a newbie to bioinformatics, and am running into the same issue when doing GSEA as described in this tread. Now and then I will get the error message:

`Error in if (abs(max.ES) > abs(min.ES)) { : missing value where TRUE/FALSE needed`

However, this is despite that I have checked the geneList to ensure that there aren't any 0's with function any(geneList == 0) or any missing values with function anyNA(geneList). The problem comes when I make changes to the gene set (TERM2GENE) and goes away when I change the minGSSize parameter to a higher value, though this is undesirable for me. Do you guys have any idea as to how I can solve this issue?

Best, Rikki

**Comment by biosilentfall** [comment]
Hello, I also experienced this error. In my case, I used metric connected based on p-value and one of the p-values was so small that during the metric calculations, produced `Inf` value. So be also sure to check `table(is.finite(gene_vector))` .

Thomas

**Comment by Rikkiff** [comment]
Thanks a bunch Thomas!
I haven't been able to find a solution yet, but your suggestion gave me
some ideas as to what it could be.

Thanks again,
Best,
Rikki
