### ISSUE TITLE
enrichGO not working for arabidopsis

### ISSUE THREAD

**Issue by huangty1208** [GuangchuangYu/clusterProfiler#21]
ego <- enrichGO(gene = gene, organism = "arabidopsis", ont = "MF", pAdjustMethod = "BH", pvalueCutoff = 0.01, qvalueCutoff = 0.05, readable = TRUE)

> ego
[1] NA

> head(gene)
[1] "820275" "828060" "827487" "819651" "838761" "837379"

No matter how I tried I always got a NA. I tried human genes from your sample data and it works fine.
Is there any issues with arabidopsis as a parameter?

**Comment by GuangchuangYu** [comment]
For Arabidopsis, you should use TAIR ID, a sample is shown below:

```r
> head(keys(org.At.tair.db))
[1] "AT1G01010" "AT1G01020" "AT1G01030" "AT1G01040" "AT1G01050" "AT1G01060"
```

more explanation can be found in the comments of [the post](http://ygc.name/2014/08/07/why-clusterprofiler-fails/).

**Comment by huangty1208** [comment]
I tried that before. Below is the results I got. 

Error in .testForValidKeys(x, keys, keytype) : 
  None of the keys entered are valid keys for 'ENTREZID'. Please use the keys method to see a listing of valid arguments.
> 

I also tried the code you posted. 
> head(keys(org.At.tair.db))
[1] "AT1G01010" "AT1G01020" "AT1G01030" "AT1G01040" "AT1G01050" "AT1G01060"
and the result is the same. 
> c
[1] "AT1G01010" "AT1G01020" "AT1G01030" "AT1G01040" "AT1G01050"
[6] "AT1G01060"

ego <- enrichGO(gene = c,
organism = "arabidopsis",
ont = "MF",
pAdjustMethod = "BH",
pvalueCutoff = 0.01,
qvalueCutoff = 0.05,
readable = TRUE)

Error in .testForValidKeys(x, keys, keytype) : 
  None of the keys entered are valid keys for 'ENTREZID'. Please use the keys method to see a listing of valid arguments.

That's why I tried to use ENTREZ ID. 
Is anything wrong with it?

**Comment by GuangchuangYu** [comment]
thanks for the report, it's due to `readable=TRUE` that try to map the gene id to gene symbol and the `EXTID2NAME` function in `DOSE` package supposed the `keytype` is `ENTREZID`.

It has been fixed in `DOSE`, see [https://github.com/GuangchuangYu/DOSE/commit/934274f234df7bd31d8813418a1d131cdb6aef3f](https://github.com/GuangchuangYu/DOSE/commit/934274f234df7bd31d8813418a1d131cdb6aef3f).

You should wait 2-3 days for Bioconductor to upload the new tarball and use `biocLite("DOSE")` to update `DOSE`.

**Comment by huangty1208** [comment]
Thanks Guangchuang. You are awesome.
