### ISSUE TITLE
Using lists vs. vectors for enrichKEGG()

### ISSUE THREAD

**Issue by VermillionAzure** [GuangchuangYu/clusterProfiler#27]
Hello,

I've found that `enrichKEGG()` seems to work with a list of Entrez gene IDs but not a vector of Entrez gene IDs, contrary to the documentation given with the package on Bioconductor right now:

Here is an R script that reproduces this behavior:

```
common_gene_ids <- readRDS('sample_genes.rds')

library(clusterProfiler)
library(org.Hs.eg.db)

print(common_gene_ids[1:10])
# [1] "DDX11L1"      "WASH7P"       "OR4F5"        "LOC729737"    "LOC100133331" "LOC100288069" "LINC00115"    "LOC643837"    "FAM41C"      
# [10] "LOC100130417"

#########################################
# Creating a mapping to Entrez gene IDs #
#########################################

# Convert the object to a list
common_to_entrez <- as.list(org.Hs.egALIAS2EG)
# Remove pathway identifiers that do not map to any entrez gene id
common_to_entrez <- common_to_entrez[!is.na(common_to_entrez)]

#################################
# Filtering of common -> Entrez #
#################################

entrez_ids <- common_to_entrez[names(common_to_entrez) %in% common_gene_ids]

class(entrez_ids)
# [1] "list"

#####################################
# Running the enrichKEGG() function #
#####################################

# This gives a result, but for a type of "list"
kegg_results <- enrichKEGG(entrez_ids, pvalueCutoff=0.05)

# On the other hand, if I try to apply this on a vector of "character..."
vector_entrez_ids <- unlist(entrez_ids)
kegg_results_vector <- enrichKEGG(vector_entrez_ids, pvalueCutoff=0.05)
# This gives me an error.
```

And here is the related RDS file, holding gene IDs:
http://s000.tinyupload.com/index.php?file_id=50396891962239121264

Please excuse me if I've made a mistake.

**Comment by GuangchuangYu** [comment]
`enrichKEGG()` only accepts a __vector of gene IDs__. 

Due to entrezgene IDs are pure numbers and some user may pass numerical vector to `enrichKEGG()`, we use `as.character()` to coerce the input gene ID as a character vector.

```r
> head(as.character(entrez_ids))
[1] "1"                                      
[2] "2"                                      
[3] "3"                                      
[4] "c(\"9\", \"1982\", \"6530\", \"10991\")"
[5] "c(\"10\", \"81539\")"                   
[6] "12"        
```

After the conversion, the list will be a character vector. In the above IDs, item 4 and 5 will be ignored when performing ID-to-KEGG mapping. So this is not the correct way.

The error in `kegg_results_vector <- enrichKEGG(vector_entrez_ids, pvalueCutoff=0.05)` is due to the `vector_entrez_ids` contains duplicated IDs.

If you use `kegg_results_vector <- enrichKEGG(unique(vector_entrez_ids), pvalueCutoff=0.05)`, it works perfectly fine.

I have added `unique()` in `DOSE` package to force it to remove all duplicated IDs, see [https://github.com/GuangchuangYu/DOSE/commit/60433ed70c58ed138714acc34446e866cb7ebca3](https://github.com/GuangchuangYu/DOSE/commit/60433ed70c58ed138714acc34446e866cb7ebca3).

**Comment by VermillionAzure** [comment]
Ah, thank you!
