### ISSUE TITLE
enrichDAVID not "transport error"

### ISSUE THREAD

**Issue by psudmant** [GuangchuangYu/clusterProfiler#35]

**Comment by psudmant** [comment]
I'm having issues with enrichDAVID - I get the below error - is the DAVID URL out of date perhaps?

Thanks in advance! Great tool! Thank you!

enrichDAVID(e_genes, idType="ENTREZ_GENE_ID", listType="Gene",annotation="GOTERM_BP_FAT", david.user="xxx")
Error in .jcall(stub, "S", "authenticate", email) : 
  org.apache.axis2.AxisFault: Transport error: 301 Error: Moved Permanently
[INFO] Unable to sendViaPost to url[http://david.abcc.ncifcrf.gov/webservice/services/DAVIDWebService.DAVIDWebServiceHttpSoap12Endpoint/]
org.apache.axis2.AxisFault: Transport error: 301 Error: Moved Permanently
	at org.apache.axis2.transport.http.HTTPSender.handleResponse(HTTPSender.java:310)
	at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:200)
	at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:76)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:400)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:225)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:435)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:402)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at sample.session.client.stub.DAVIDWebServiceStub.authenticate(DAVIDWebServiceStub.java:2288)

**Comment by GuangchuangYu** [comment]
see the discussion in [https://support.bioconductor.org/p/70090/](https://support.bioconductor.org/p/70090/).

We need to wait for update of RDAVIDWebService package since DAVID changed to a new url.

BTW: DAVID's data is out-of-date, you can refer to discussion in:
+ [http://ygc.name/2015/03/16/david-functional-analysis-with-clusterprofiler/](http://ygc.name/2015/03/16/david-functional-analysis-with-clusterprofiler/)
+ [http://ygc.name/2015/02/01/kegg-enrichment-analysis-with-latest-online-data-using-clusterprofiler/](http://ygc.name/2015/02/01/kegg-enrichment-analysis-with-latest-online-data-using-clusterprofiler/)
+ [http://ygc.name/2015/08/13/functional-enrichment-for-gtex-paper/](http://ygc.name/2015/08/13/functional-enrichment-for-gtex-paper/).

I recommend you using `enrichGO` and `enrichKEGG` instead of DAVID for functional analysis.

**Comment by psudmant** [comment]
Thanks! Yes, I've read these and I JUST figured out how to get RDAVIDWebService working. Your points regarding DAVID being out of date are great too, though, I wanted to try it out.

You might consider updating: http://david.abcc.ncifcrf.gov/webservice/services/DAVIDWebService.DAVIDWebServiceHttpSoap12Endpoint/ to https://david.ncifcrf.gov/webservice/services/DAVIDWebService.DAVIDWebServiceHttpSoap12Endpoint/ though, I can understand wanting to wait until the next RDAVIDWebService release

cheers.

**Comment by GuangchuangYu** [comment]
@psudmant I found that the package source is not updated since 2 year ago. To use david service, we need to provide the updated url manually.

I have updated the url and it works.

![_ hmiw d67 7 du siqnb](https://cloud.githubusercontent.com/assets/626539/14376272/b48f393a-fd9a-11e5-9009-82d3fd5e65e6.jpg)

**Comment by psudmant** [comment]
Great! Thanks! I took your advice and used enrichGO and enrichKEGG instead. Wonderful tool, thanks so much!

**Comment by maperezm** [comment]
Which is the difference between these functions? enrichDAVID and enrichGO
